import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    backgroundImage: {
        flex: 1,
        resizeMode: 'cover',
    },
    container: {
        flex: 1,
        padding: 10,
        paddingTop: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    messagesContainer: {
        flex: 1,
    },
    messagesContent: {
        paddingBottom: 20,
    },
    trainerMessage: {
        marginBottom: 20,
    },
    userMessage: {
        marginBottom: 20,
    },
    lastMessage: {
        marginBottom: 10,
    },
    messageWrapper: {
        flexDirection: 'column',
    },
    trainerMessageContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    userMessageContainer: {
        flexDirection: 'row-reverse',
        alignItems: 'flex-start',
    },
    trainerAvatar: {
        width: 35,
        height: 35,
        borderRadius: 18,
        marginRight: 10,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    userAvatar: {
        width: 35,
        height: 35,
        borderRadius: 18,
        marginLeft: 10,
        borderWidth: 2,
        borderColor: 'rgba(3, 201, 136, 0.3)',
    },
    trainerBubble: {
        padding: 15,
        maxWidth: '80%',
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    userBubble: {
        backgroundColor: '#03C988',
        padding: 15,
        borderRadius: 20,
        maxWidth: '80%',
        marginRight: 10,
        shadowColor: '#03C988',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    trainerText: {
        color: '#fff',
        fontSize: 16,
        lineHeight: 22,
    },
    userText: {
        color: '#fff',
        fontSize: 16,
        lineHeight: 22,
        fontWeight: '500',
    },
    videoContainer: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 15,
        overflow: 'hidden',
        marginVertical: 10,
        marginLeft: 45,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    webView: {
        flex: 1,
        borderRadius: 15,
    },
    imageContainer: {
        marginVertical: 10,
        marginLeft: 45,
        borderRadius: 15,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    capturedImage: {
        width: 250,
        height: 150,
        borderRadius: 15,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: 15,
        paddingRight: 10,
        paddingVertical: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 25,
        marginHorizontal: 5,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    loadingInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
    },
    loadingText: {
        color: '#03C988',
        fontSize: 16,
        marginLeft: 10,
        fontWeight: '500',
    },
    cameraButton: {
        marginHorizontal: 5,
        marginVertical: 5,
        padding: 5,
    },
    cameraIcon: {
        width: 24,
        height: 24,
        tintColor: 'rgba(255, 255, 255, 0.7)',
    },
    input: {
        flex: 1,
        padding: 12,
        borderRadius: 20,
        color: '#fff',
        fontSize: 16,
        maxHeight: 100,
    },
    sendButton: {
        backgroundColor: '#03C988',
        padding: 12,
        borderRadius: 20,
        marginLeft: 10,
        shadowColor: '#03C988',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    sendButtonDisabled: {
        backgroundColor: 'rgba(3, 201, 136, 0.3)',
        shadowOpacity: 0.1,
    },
    sendIcon: {
        width: 20,
        height: 20,
        tintColor: '#fff',
    },
    topNavContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 65,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        paddingVertical: 15,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    backButton: {
        padding: 10,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    backIcon: {
        width: 24,
        height: 24,
        tintColor: '#fff',
    },
    titleContainer: {
        flex: 1,
        alignItems: 'center',
        marginHorizontal: 10,
    },
    chatTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    chatSubtitle: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 12,
        textAlign: 'center',
        marginTop: 2,
    },
    pointsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 20,
        backgroundColor: 'rgba(3, 201, 136, 0.2)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: 'rgba(3, 201, 136, 0.3)',
    },
    pointsIcon: {
        width: 20,
        height: 20,
        marginRight: 5,
    },
    pointsText: {
        color: '#03C988',
        fontSize: 16,
        fontWeight: 'bold',
    },
    emptyStateContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        paddingHorizontal: 40,
    },
    emptyStateAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 20,
        borderWidth: 3,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    emptyStateText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    emptyStateSubtext: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 22,
    },
    cameraContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black',
    },
    cameraPreview: {
        flex: 1,
        justifyContent: 'flex-end',
        width: '100%',
        height: '100%',
    },
    captureButtonContainer: {
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 30,
    },
    captureButton: {
        backgroundColor: '#fff',
        borderRadius: 30,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    captureButtonText: {
        fontSize: 16,
        color: '#000',
        fontWeight: 'bold',
    },
    LoadingPagecontainer:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    Loading_backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -1,
        backgroundColor: 'black'
    },
    Loading_fallbackBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -2,
    },
    Loading_container: {
        position: 'absolute',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 70,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        width: '100%',
    },
    loadingTrainerAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 30,
        borderWidth: 4,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    Loading_welcomeText: {
        color: '#fff',
        fontSize: 24,
        textAlign: 'center',
        marginBottom: 15,
        marginHorizontal: 40,
        fontWeight: 'bold',
    },
    Loading_subtitleText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 30,
        marginHorizontal: 40,
        lineHeight: 22,
    },
    Loading_statusText: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 15,
    },
    progressBarContainer: {
        width: '80%',
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressBar: {
        height: 6,
        backgroundColor: '#03C988',
        borderRadius: 3,
    },
    exerciseContainer: {
        marginTop: 15,
        marginLeft: 45,
    },
    exerciseDetailsBox: {
        padding: 15,
        borderRadius: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    exerciseTitle: {
        fontSize: 16,
        color: '#03C988',
        fontWeight: 'bold',
        marginBottom: 10,
        textAlign: 'center',
    },
    exerciseDetailsText: {
        fontSize: 14,
        color: '#FFF',
        lineHeight: 20,
        marginBottom: 5,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 10,
    },
    completedButton: {
        borderWidth: 1,
        borderColor: '#03C988',
        backgroundColor: 'rgba(3, 201, 136, 0.1)',
        padding: 10,
        borderRadius: 20,
        marginHorizontal: 5,
        minWidth: 100,
        alignItems: 'center',
    },
    tutorialButton: {
        borderWidth: 1,
        borderColor: '#03C988',
        backgroundColor: 'rgba(3, 201, 136, 0.1)',
        padding: 10,
        borderRadius: 20,
        marginHorizontal: 5,
        minWidth: 100,
        alignItems: 'center',
    },
    buttonText: {
        fontSize: 14,
        color: '#03C988',
        fontWeight: '500',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -1,
    },
    loadingContent: {
        position: 'absolute',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 70,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        width: '100%',
    },
    loadingAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 30,
        borderWidth: 4,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    progressContainer: {
        width: '80%',
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 3,
        overflow: 'hidden',
        marginTop: 20,
    },
    progressBar: {
        height: 6,
        backgroundColor: '#03C988',
        borderRadius: 3,
    },
    progressFill: {
        height: 6,
        backgroundColor: '#03C988',
        borderRadius: 3,
    },
    background: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 65,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        paddingVertical: 15,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    headerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginHorizontal: 10,
    },
    trainerInfo: {
        flex: 1,
    },
    trainerName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    trainerTitle: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 12,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        paddingHorizontal: 40,
    },
    emptyAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 20,
        borderWidth: 3,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    emptyTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    emptySubtitle: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 22,
    },
    messageContainer: {
        marginBottom: 20,
    },
    messageBubble: {
        padding: 15,
        maxWidth: '80%',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    messageAvatar: {
        width: 35,
        height: 35,
        borderRadius: 18,
        marginRight: 10,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    messageText: {
        fontSize: 16,
        lineHeight: 22,
    },
    messageImage: {
        width: 250,
        height: 150,
        borderRadius: 15,
    },
    pointsEarned: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
    },
    smallPointsIcon: {
        width: 16,
        height: 16,
        marginRight: 5,
    },
    pointsEarnedText: {
        color: '#03C988',
        fontSize: 14,
        fontWeight: 'bold',
    },
    exerciseCard: {
        marginTop: 15,
        padding: 15,
        borderRadius: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    exerciseDetails: {
        fontSize: 14,
        color: '#FFF',
        lineHeight: 20,
        marginBottom: 15,
        textAlign: 'center',
    },
    tutorialButtonText: {
        fontSize: 14,
        color: '#03C988',
        fontWeight: '500',
    },
    completeButton: {
        borderWidth: 1,
        borderColor: '#03C988',
        backgroundColor: 'rgba(3, 201, 136, 0.1)',
        padding: 10,
        borderRadius: 20,
        marginTop: 10,
        alignItems: 'center',
    },
    completeButtonText: {
        fontSize: 14,
        color: '#03C988',
        fontWeight: '500',
    },
    video: {
        flex: 1,
        borderRadius: 15,
    },
    loadingMessage: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    loadingMessageText: {
        color: '#fff',
        fontSize: 16,
        marginLeft: 10,
    },
    cameraControls: {
        position: 'absolute',
        bottom: 30,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    cameraButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    captureButtonInner: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#fff',
    },
});

export default styles;
